### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by isfaaghyth** [ramdanisource/komunikasi-antar-fragment#1]
ki, sebaiknya class interface dipisah saja :D

**Comment by ramdanisource** [comment]
ok sudah direfactor @isfaaghyth :D, please check commit [https://github.com/ramdanisource/komunikasi-antar-fragment/commit/7ab14270ebb0d2f532223f7622d2df1c488efdf4](https://github.com/ramdanisource/komunikasi-antar-fragment/commit/7ab14270ebb0d2f532223f7622d2df1c488efdf4)
